#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""I2-B: catalog metrics consistency tests.

Verifies catalog_metrics.json is machine-generated, counts are consistent with
the actual data files, and no double counting exists between countries and
non-country entities.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "data" / "intelligence" / "africa"

PASS = FAIL = 0


def check(name, cond, detail=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  [PASS] {name}")
    else:
        FAIL += 1
        print(f"  [FAIL] {name}  ({detail})")


def load(name):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def main():
    metrics = load("catalog_metrics.json")
    regions = load("regions.json")["regions"]
    countries = load("countries.json")["countries"]
    entities = load("entities.json")["entities"]
    rels = load("relationships.json")["relationships"]
    sources = load("sources.json")["sources"]
    evidence = load("evidence_records.json")["evidence"]
    profiles = load("relation_profiles.json")["profiles"]

    eids = [e["entity_id"] for e in entities]
    cids = [c["country_id"] for c in countries]

    check("metrics schema version", metrics.get("schema_version", "").startswith("asip-catalog-metrics-v"))
    check("metrics generated by script", "gen_i2b_migration.py" in metrics.get("generated_by", "") or "i3d1_import.py" in metrics.get("generated_by", "") or "i3d2_import.py" in metrics.get("generated_by", "") or "depth_a_import.py" in metrics.get("generated_by", "") or "depth_b_import.py" in metrics.get("generated_by", "") or "depth_c_import.py" in metrics.get("generated_by", "") or "depth_d_import.py" in metrics.get("generated_by", "") or "depth_e_import.py" in metrics.get("generated_by", ""))
    check("region_count consistent", metrics["region_count"] == len(regions))
    check("country_count consistent", metrics["country_count"] == len(countries))
    check("non_country_entity_count consistent", metrics["non_country_entity_count"] == len(entities))
    check("no country duplicates in entities.json", not (set(eids) & set(cids)),
          str(set(eids) & set(cids)))
    check("unique_knowledge_object_count = r+c+e",
          metrics["unique_knowledge_object_count"] == len(regions) + len(countries) + len(entities))
    check("entity_page_count == non_country entities", metrics["entity_page_count"] == len(entities))
    check("country_page_count == countries", metrics["country_page_count"] == len(countries))
    check("relationship_count consistent", metrics["relationship_count"] == len(rels))
    check("relation_profile_count consistent", metrics["relation_profile_count"] == len(profiles))
    check("source_count consistent", metrics["source_count"] == len(sources))
    check("evidence_record_count consistent", metrics["evidence_record_count"] == len(evidence))
    ev_status = {}
    for e in evidence:
        ev_status[e["verification_status"]] = ev_status.get(e["verification_status"], 0) + 1
    check("evidence_by_status consistent", metrics["evidence_by_status"] == ev_status, str(ev_status))
    # totals
    tot = sum(metrics["evidence_by_status"].values())
    check("evidence status sums to total", tot == len(evidence), f"{tot} vs {len(evidence)}")
    check("evidence verified count honest (>=1, <70% of total, not inflated)",
          0 < metrics["evidence_by_status"].get("verified", 0) < metrics["evidence_record_count"] * 0.7)
    # I3-B: manual-source-mapped evidence is now the majority; generated records
    # must never be verified.
    check("manual evidence is substantial (I3-B >=45)",
          metrics["evidence_manual_count"] >= 45, str(metrics["evidence_manual_count"]))
    check("no generated evidence verified",
          metrics["evidence_by_status"].get("verified", 0) <= metrics["evidence_record_count"] - metrics["evidence_generated_count"])
    check("profile_depth counts sum to entities", sum(metrics["profile_depth_count"].values()) == len(entities))
    # I3-A: content deepening moves the distribution from "1 encyclopedia" to a
    # content-backed majority (>=12 full, <=10 basic). Honest = bounded by total.
    check("encyclopedia_full backed by content (I3-A >=12)",
          12 <= metrics["encyclopedia_full_count"] <= len(entities), str(metrics["encyclopedia_full_count"]))
    check("basic entries remain a minority (I3-A <=10)",
          metrics["basic_entry_count"] <= 10, str(metrics["basic_entry_count"]))
    check("route_count positive", metrics["route_count"] > 100)
    check("counting note present", bool(metrics.get("counting_note")))

    print(f"\ntest_africa_metrics: PASS={PASS} FAIL={FAIL}")
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
