#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Inspect exact failing assertions across 5 tests."""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path("C:/Users/kenan/WorkBuddy/clean/asip-intelligence-v10-i3d1")
PY = Path(sys.executable)

# ev-d1-005 / 006 / 007 / 009 / 013 fields
evidence = json.load(open(ROOT / "data/intelligence/africa/evidence_records.json", encoding="utf-8"))["evidence"]
sources = {s["source_id"]: s for s in json.load(open(ROOT / "data/intelligence/africa/sources.json", encoding="utf-8"))["sources"]}
for e in evidence:
    if e["evidence_id"] in ("ev-d1-005", "ev-d1-006", "ev-d1-007", "ev-d1-009", "ev-d1-013"):
        s = sources.get(e["source_id"], {})
        print(e["evidence_id"], e["claim_id"], "| src:", e["source_id"], "| ev.source_published_at:", e.get("source_published_at"), "| src.published_at:", s.get("published_at"), "| locator:", bool(e.get("source_locator")))

# which tests assert what
print("\n--- test_i3b_evidence_upgrade :pub rule ---")
text = (ROOT / "scripts/tests/intelligence/test_i3b_evidence_upgrade.py").read_text(encoding="utf-8")
for i, line in enumerate(text.splitlines(), 1):
    if "pub" in line and ("check" in line or "fail" in line or "published" in line):
        print(i, line.strip()[:160])

print("\n--- test_africa_metrics profile_depth rule ---")
text = (ROOT / "scripts/tests/intelligence/test_africa_metrics.py").read_text(encoding="utf-8")
for i, line in enumerate(text.splitlines(), 1):
    if "profile_depth" in line or "generated by" in line:
        print(i, line.strip()[:160])

print("\n--- test_i3a_source_coverage full output ---")
r = subprocess.run([str(PY), str(ROOT / "scripts/tests/intelligence/test_i3a_source_coverage.py")], capture_output=True, text=True, encoding="utf-8")
for line in r.stdout.splitlines():
    if "FAIL" in line:
        print(line.strip()[:200])

print("\n--- test_i3b_release_candidate manifest source ---")
text = (ROOT / "scripts/tests/intelligence/test_i3b_release_candidate.py").read_text(encoding="utf-8")
for i, line in enumerate(text.splitlines(), 1):
    if "manifest" in line.lower() and ("json" in line or "load" in line or "path" in line):
        print(i, line.strip()[:160])
